services:
  db:
    image: postgres:15
    container_name: auditoria-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  redis:
    image: redis:7.4-alpine
    container_name: auditoria-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  api:
    build:
      context: ./api
      args:
        NPM_CONFIG_PROXY: ${NPM_CONFIG_PROXY:-}
        NPM_CONFIG_HTTPS_PROXY: ${NPM_CONFIG_HTTPS_PROXY:-}
        NPM_CONFIG_REGISTRY: ${NPM_CONFIG_REGISTRY:-}
    container_name: auditoria-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      PORT: ${API_PORT:-4000}
      FILE_STORAGE_PATH: ${FILE_STORAGE_PATH:-/usr/src/app/storage}
      CLIENT_URL: ${CLIENT_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      SURVEY_REMINDER_DAYS: ${SURVEY_REMINDER_DAYS:-3}
      CORS_ALLOWLIST: ${CORS_ALLOWLIST:-*}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-60000}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-300}
      LOGIN_RATE_LIMIT_WINDOW_MS: ${LOGIN_RATE_LIMIT_WINDOW_MS:-900000}
      LOGIN_RATE_LIMIT_MAX: ${LOGIN_RATE_LIMIT_MAX:-10}
      PRISMA_LOG: query,error,warn
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${API_PORT:-4000}:4000"
    volumes:
      - api-storage:/usr/src/app/storage
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${API_PORT:-4000}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  web:
    build:
      context: ./web
      args:
        NPM_CONFIG_PROXY: ${NPM_CONFIG_PROXY:-}
        NPM_CONFIG_HTTPS_PROXY: ${NPM_CONFIG_HTTPS_PROXY:-}
        NPM_CONFIG_REGISTRY: ${NPM_CONFIG_REGISTRY:-}
    container_name: auditoria-web
    restart: unless-stopped
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:4000/api}
    depends_on:
      - api
    ports:
      - "${WEB_PORT:-5173}:5173"

volumes:
  postgres-data:
  api-storage:
