version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auditoria
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build: ./api
    command: npm run start
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/auditoria
      JWT_SECRET: super-secret
      JWT_REFRESH_SECRET: super-refresh
      PORT: 4000
      FILE_STORAGE_PATH: /usr/src/app/storage
      CLIENT_URL: http://localhost:5173
    depends_on:
      - db
    ports:
      - '4000:4000'
    volumes:
      - api-storage:/usr/src/app/storage
  web:
    build: ./web
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://localhost:4000/api
    depends_on:
      - api
volumes:
  postgres-data:
  api-storage:
