import { Router } from 'express';

import { authRouter } from './modules/auth/auth.router';
import { projectRouter } from './modules/projects/project.router';
import { companyRouter } from './modules/companies/company.router';
import { dataRequestRouter } from './modules/dataRequest/data-request.router';
import { dataRequestCategoryRouter } from './modules/dataRequestCategories/data-request-category.router';
import { formsRouter } from './modules/forms/forms.router';
import { processRouter } from './modules/processes/process.router';
import { processCatalogRouter } from './modules/processCatalog/process-catalog.router';
import { sopRouter } from './modules/sops/sop.router';
import { checklistRouter } from './modules/checklists/checklist.router';
import { findingRouter } from './modules/findings/finding.router';
import { actionRouter } from './modules/actions/action.router';
import { systemsRouter } from './modules/systems/systems.router';
import { receptionRouter } from './modules/receptions/reception.router';
import { pocRouter } from './modules/poc/poc.router';
import { decisionRouter } from './modules/decisions/decision.router';
import { kpiRouter } from './modules/kpis/kpi.router';
import { committeeRouter } from './modules/governance/committee.router';
import { meetingRouter } from './modules/governance/meeting.router';
import { scopeChangeRouter } from './modules/governance/scope-change.router';
import { minuteRouter } from './modules/governance/minute.router';
import { approvalRouter } from './modules/governance/approval.router';
import { userRouter } from './modules/users/user.router';
import { exportRouter } from './modules/export/export.router';
import { auditRouter } from './modules/audit/audit.router';
import { fileRouter } from './modules/files/file.router';
import { projectPlanRouter } from './modules/projectPlan/project-plan.router';
import { reportRouter } from './modules/reports/report.router';
import { interviewRouter } from './modules/interviews/interview.router';
import { inventoryRouter } from './modules/inventory/inventory.router';
import { fiveSRouter } from './modules/fiveS/five-s.router';
import { hseRouter } from './modules/hse/hse.router';
import { layoutRouter } from './modules/layout/layout.router';
import { routesRouter } from './modules/routes/routes.router';

const appRouter = Router();

appRouter.use('/auth', authRouter);
appRouter.use('/projects', projectRouter);
appRouter.use('/companies', companyRouter);
appRouter.use('/data-request', dataRequestRouter);
appRouter.use('/data-request-categories', dataRequestCategoryRouter);
appRouter.use('/forms', formsRouter);
appRouter.use('/process-assets', processRouter);
appRouter.use('/processes', processCatalogRouter);
appRouter.use('/sops', sopRouter);
appRouter.use('/checklists', checklistRouter);
appRouter.use('/findings', findingRouter);
appRouter.use('/actions', actionRouter);
appRouter.use('/systems', systemsRouter);
appRouter.use('/receptions', receptionRouter);
appRouter.use('/poc', pocRouter);
appRouter.use('/decisions', decisionRouter);
appRouter.use('/kpis', kpiRouter);
appRouter.use('/committees', committeeRouter);
appRouter.use('/meetings', meetingRouter);
appRouter.use('/minutes', minuteRouter);
appRouter.use('/scope-changes', scopeChangeRouter);
appRouter.use('/approvals', approvalRouter);
appRouter.use('/users', userRouter);
appRouter.use('/export', exportRouter);
appRouter.use('/audit', auditRouter);
appRouter.use('/files', fileRouter);
appRouter.use('/project-plan', projectPlanRouter);
appRouter.use('/reports', reportRouter);
appRouter.use('/interviews', interviewRouter);
appRouter.use('/inventory', inventoryRouter);
appRouter.use('/fiveS', fiveSRouter);
appRouter.use('/hse', hseRouter);
appRouter.use('/layout', layoutRouter);
appRouter.use('/routes', routesRouter);

export { appRouter };
